### Linear Regression with multiple variables a.k.a multivariate regression

In [3]:
import pandas as pd 
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from io import StringIO
import math

In [4]:
df = pd.read_csv("C:/Users/sar/Downloads/homeprices.csv")

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

#### NaN value fill karne ke liye acc to reqerment fill kar skte hai yha mai median le ke fill karenge 

In [6]:
df.bedrooms.median()

4.0

In [7]:
df.describe()

area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [8]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median()) # bedrooms ke columns me jaha bhi NaN value hogi bedrooms ke mean se fill hom jayegi (dynamic)

In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
df.describe()

area  bedrooms        age          price
count     6.000000  6.000000   6.000000       6.000000
mean   3416.666667  4.166667  16.500000  648333.333333
std     587.934237  1.169045   8.288546  109117.673484
min    2600.000000  3.000000   8.000000  550000.000000
25%    3050.000000  3.250000   9.750000  572500.000000
50%    3400.000000  4.000000  16.500000  602500.000000
75%    3900.000000  4.750000  19.500000  722500.000000
max    4100.000000  6.000000  30.000000  810000.000000

In [11]:
model = linear_model.LinearRegression()               
model.fit(df.drop('price',axis = 'columns'),df.price)

# fit() function model ko train karne ke lliye hota hai multidimension me fit() me do variable pass karna hota  1st all feature jitna bhi 
# independent feature hai vo dusra target columns it means dependent columns  ab yaha  poora dataframe to pass nahi karte kyuki
# usme independent and dependent  variable dono hai dono ko alg alg pass krna pdta hai  to pahla vale me poora datafram pass krne ka tarika hai jiss 
# ji dependent hai usko drop kr do or vo internalnya dataframe ban jayega or usme pass ho jayega kar nahi  skte 

LinearRegression()

In [12]:
# ab model train ho gya hai 
# predict karte hai 300 area 3 bedroom and age 40

model.predict([[300,4,40]]) # data 2d array me pass krna hota hai 

C:\Users\sar\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([219228.53841448])

In [13]:
model.predict([[1300,4,1]])

C:\Users\sar\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([457327.9787933])

In [ ]:
# y = mx + b 


In [14]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
model.intercept_

221323.0018654043

In [16]:
112.06244194*1300+23388.88007794*4-3231.71790863*1+221323.0018654043

457327.9787905343

In [17]:
# ab y = mx + b se chek karte hai model shi predict kr raha hai yua nahi 

model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
model.intercept_

221323.0018654043

In [19]:
# ab isne calculation ki kaise vo chek krte hai 

112.06244194*300+23388.88007794*4-3231.71790863*40+221323.0018654043

219228.53841396433

## SAVE AND LOAD TRAINED MODEL  USING ,

## 1 PICKLE
## 2 SKLEARN JOBLIB

In [20]:
import pickle 

In [23]:
with open('model_pickle','wb')as file:
    pickle.dump(model,file)

In [24]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [25]:
mp.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [27]:
mp.intercept_

221323.0018654043

In [29]:
mp.predict([[1300,4,1]])

C:\Users\sar\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([457327.9787933])

In [33]:
!pip install joblib

In [34]:
import joblib

In [36]:
import joblib

# Serialize
joblib.dump(model, 'model_joblib')

# Deserialize
mj= joblib.load('model_joblib')


In [37]:
mj.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [38]:
mj.intercept_

221323.0018654043

In [39]:
mj.predict([[1300,4,1]])

C:\Users\sar\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([457327.9787933])

### difrence btw joblib and pickle 

### While Pickle is suitable for smaller objects, Joblib is more efficient when dealing with large NumPy arrays.